### ISSUE TITLE
Issue with spliceAI output for some indels

### ISSUE THREAD

**Issue by HLSZim** [broadinstitute/SpliceAI-lookup#1]
Hi, 

I've run into difficulty getting spliceAI output for a couple of indels. The API appears to be pulling the correct genomic position and variant nomenclature for my input variant, but I see periods in the output instead of spliceAI scores and positions. I've attached an image for NM_005591.3(MRE11A):c.1225_1225+1delinsCA to illustrate this issue. If I change this to NM_005591.3(MRE11A):c.1225_1225+1del or NM_005591.3(MRE11A):c.1225delinsC, I do get scores. A similar issue is seen with 
NM_000051.3(ATM): c.6808_6810delinsTTT and NM_000038.5 (APC):c.5267_5268delinsTG.
![image](https://user-images.githubusercontent.com/69170004/89224696-c4f95100-d58d-11ea-8e3e-02afa38d5db2.png)

Is this user error on my end?

Thanks, 
Heather

**Comment by bw2** [comment]
Hi Heather, thanks for posting this issue.
I've added an error message for this, since SpliceAI [doesn't currently process](https://github.com/Illumina/SpliceAI/blob/master/spliceai/utils.py#L138-L140) these kinds of variants.

![image](https://user-images.githubusercontent.com/6240170/90123233-7cc7f480-dd2c-11ea-9ad0-eb3f63082573.png)

You may want to post a feature request to https://github.com/Illumina/SpliceAI/issues

**Comment by bw2** [comment]
MNP support has now been implemented (via https://github.com/bw2/SpliceAI) thanks to [@kdahlo](https://github.com/Illumina/SpliceAI/pull/119)
