### ISSUE TITLE
Differing predictions for same sequence

### ISSUE THREAD

**Issue by NM-G08** [broadinstitute/SpliceAI-lookup#31]
To Whom It May Concern,

A colleague and I were looking at the predictions for NM_000059.3(BRCA2):c.8488_8496dup.  We put in [13:32945090-C-CAGTGGATGG](https://spliceailookup.broadinstitute.org/#variant=13%3A32945090-C-CAGTGGATGG&hg=37&distance=10000&mask=0&precomputed=0) based on what we are seeing in the NGS reads for a patient.  However, HGVS nomenclature also allows this alteration to be be written as [13:32945092-G-GTGGATGGAG](https://spliceailookup.broadinstitute.org/#variant=13%3A32945092-G-GTGGATGGAG&hg=37&distance=10000&mask=0&precomputed=0).  Both results show an acceptor loss (at g.32945093, which is the canonical acceptor splice site), but 13:32945090-C-CAGTGGATGG shows an acceptor gain at g.32945090 (c.8488-3, after AC sequence) whereas 13:32945092-G-GTGGATGGAG shows an acceptor gain at g.32945092 (unsure if this is meant to be c.8488-1, after CA sequence or actually meant to represent restoration of the canonical acceptor splice site - even though it's not g.3294093 - which isn't directly affected by this duplication in the first place).  Finally, when I run NM_000059.3(BRCA2):c.8488_8496dup itself, it converts this to [13-32945101-G-GTGGATGGAG](https://spliceailookup.broadinstitute.org/#variant=NM_000059.3(BRCA2)%3Ac.8488_8496dup&hg=37&distance=10000&mask=0&precomputed=0) and splicing is totally normal.

Could you help us determine:
1) Why all of these alterations which ultimately result in the same sequence (c.8488-10-ATTATTACAGTGGATGGAGTGGATGGAG) yield different splicing predictions?
2) Which is the most accurate prediction?
3) Is there a format we should use consistently to ensure we are getting the most accurate prediction?  I've never noticed before, but I wonder if other indels, particularly those that can occur/be written in multiple ways due to the HGVS 3' rule, also show discrepant predictions.

Thank you!
NM

**Comment by bw2** [comment]
It took me a while to trace this.. and I'm still not sure what the root cause is, but at least have some clues. I've confirmed that spliceAI uses the exact same sequence for the ref and alt alleles in all 3 versions of this variant (except for a handful of bases at the very ends of the window, since the middle position of the window is shifting, but this doesn't affect the prediction). I think the key is the issue you found with the acceptor gain position being inconsistent. In my dev version, I added columns that show the raw underlying probabilities for the ref and alt haplotypes (from which the delta score is computed). This is what they look like for the 3 variants:

<img width="1572" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/5ec0bbf8-97f4-4f5c-a596-1bfc1dc67e4e">
<img width="1568" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/0070a8af-7dd1-4481-bf11-d4414556d4f9">
<img width="1568" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/d58b2714-8427-49f1-82d4-55134b25f63b">
So for the last one (NM_000059.3(BRCA2):c.8488_8496dup), the predicted probabilities remain the same, but their positions now line up, so they cancel each other out. 
That's as far as I got. 
What do you think?  
Should we show raw probabilities like in these screenshots?

**Comment by NM-G08** [comment]
Hello bw2,

I'm not sure I follow.  The 323709XX value represents the start of the duplication, so I understand that the middle position would be shifted between the three entries you pictured above.  However, only the second and third seem to be using the same ref and alt alleles.  I also can't understand why a handful of bases at the "end of the window" would be different; perhaps I'm not clear about what the end of the window signifies and has to do with what part of the sequence is used in the algorithm versus the sequence in the end of the window actually being part of the duplication.

Anyway, based on what you are saying about the probabilities, I see what's happening.  What I am understanding from the pre-mRNA positions is that in the 3rd one (i.e., correct/aligned probabilities), the pre-mRNA position corresponds to the base pair right after the canonical acceptor AG; this is consistent with the pre-mRNA position if I created a splice site variant within the canonical acceptor splice site itself (https://spliceailookup.broadinstitute.org/#variant=13-32370955-G-A&hg=38&distance=50&mask=0&precomputed=0).  However, for the first two, 3bp and 1bp align with where we would expect the pre-mRNA position prediction to occur; 0bp for the gain represents a gain/splice in between the A and G of the AG canonical splice site.  Perhaps if you can figure out why that incorrect positioning is occurring for the gain, you could make the algorithm consistent.

Please let me know if there are follow-up questions.

Thanks so much for looking into this!
NM

**Comment by bw2** [comment]
Hi @NM-G08 , 
I meant that SpliceAI predictions are based on a +/- 5000 base pair window around the variant position (eg. it takes 10,000 bases of sequence and passes that to the neural net), so when you shift the variant position (eg. the center of the window), the edges of this window also shift. The model then outputs probabilities for each position in the window. I doubt this shift in the edges significantly affects the predictions for bases far away from the edges. 

"Perhaps if you can figure out why that incorrect positioning is occurring for the gain, you could make the algorithm consistent."   I wasn't able to figure out if this is a problem with the neural net model, or with the code that converts its output into delta scores. @kdahlo has spent a lot more time than me looking at how SpliceAI handles indels. Perhaps they can weigh in on this.

**Comment by kdahlo** [comment]
Confirming @bw2 - SpliceAI is measuring is the change (delta) between the values of the ref sequence and the values of alt sequence, then showing you the sites with the maximum change between ref and alt. For for SNVs, this is a simpler comparison. For indels however, this also means that there is an alignment implied by the way you input the mutation. In the first case you are asking SpliceAI to compare the new sequence to the C at site 13:32945090, and in the other case you are asking SpliceAI to compare the new sequence to the G at site 13:32945092, and in the final form you are comparing to the G at site 13:32945101. One option would be to look at the underlying scores (ref p, alt p) for each sequence, as @bw2 has done in his response. Another option is to decide on a consistent way to represent indels, for example always aligning them to the 3' end as you mention.

Researching a related problem, I considered the possibility of "fixing the alignment" in cases like this to make results consistent - unfortunately, for different researchers and situations, the correct fix could vary. I think unfortunately the best solution is just to be aware that different alignments create different interpretations. 

As a side note, if you are using SpliceAI to look for splice sites across a long sequence and not splicing _changes_ caused by mutations, delta scores are not the right tool. It is possible to use Splice AI to produce scores for each base of long sequences, and that might be preferable for careful examination of a specific sequence.

One thing I notice is that in this case is that the sequence is repetitive, completely encompasses the splice site, and includes multiple canonical splice motifs. I think you might see similar problems in other regions with these qualities because there are actually multiple possible splice sites, and SpliceAI delta scores are giving you a maximum relative to a specific site, not the full picture of the all the competing splice sites in your sequence.

I hope this helps, I think you are definitely looking at a mutation that has the potential to impact splicing, it just seems a little more complex than the typical case for SpliceAI delta scores.

**Comment by NM-G08** [comment]
@kdahlo Thanks for testing out the option of "fixing the alignment".  If there is a chance it won't work for everyone, I agree that the best solution for us is to ensure we are putting in the HGVS-compliant nomenclature.

However, would you mind taking a look at the example one more time.  I actually thought that the reason for the different predictions was because the pre-mRNA position was wrong.

1. ![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/8aa39641-17b7-47cc-aab7-569a548581b9)
In this case, the acceptor loss is at c.8488 (g.32370953+3=canonical AG) and the acceptor gain is at c.8488-3 (following TA sequence, not AG).  I've highlighted the respective nucleotides in the image below (not between the vertical lines).
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/d6f68cbd-c4ee-44d3-b444-a98868f4148d)

2. ![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/0c2e395f-63de-493d-ade1-61d1a22d5264)
In this case, the acceptor loss is at c.8488 (g.32370955+1=canonical AG) and the acceptor gain is at c.8488-1 (following CA sequence, not AG).  Again, I've highlighted the respective nucleotides in the image below.
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/a88f40ef-fe64-4e6b-94d1-45ae790d31e5)

3. ![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/3c55911f-b8ee-4547-beb1-8eaa68df223a)
It's only in this case that the acceptor loss and gain are correctly predicted for AG sequence and are both at c.8488 (g.32370964-8=canonical AG).
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/eae79567-927c-4918-a56a-6960b1f251ab)

This is why I wondered if there was a bug causing the pre-mRNA position to be off because of indels, as opposed to it being related to the initial genomic position delineating different window frames or there actually being the possibility of multiple possible splice sites.

Thanks,
NM

PS - Re: "As a side note, if you are using SpliceAI to look for splice sites across a long sequence and not splicing changes caused by mutations, delta scores are not the right tool. It is possible to use Splice AI to produce scores for each base of long sequences, and that might be preferable for careful examination of a specific sequence.", I do actually have a feature request for this in [](https://github.com/broadinstitute/SpliceAI-lookup/issues/30).

*The above images (excluding SpliceAI screenshots) are from Alamut Visual Plus version v1.7.1 | © 2023 SOPHiA GENETICS.

**Comment by baumanale** [comment]
Hello @NM-G08 and hello @kdahlo !

we have encountered a similar case as @NM-G08 with a longer insertion and think we can explain the results ([https://spliceailookup.broadinstitute.org/#variant=chr5-112800732-T-TAACAGATGGTGAGGGGAGGAGCCAAGATGGCCGAATAGGAACAGCTCCGGTCTACAGCTCCCAGCGTGAGCGACGCAGAAGACGGTGATTTCTGCATTTCCATCTGAGGTACCGGGTTCATCTCACTAGGGAGTGCCAGACAGTGGGCGCAGGCCA&hg=38&distance=10000&mask=0](https://spliceailookup.broadinstitute.org/#variant=chr5-112800732-T-TAACAGATGGTGAGGGGAGGAGCCAAGATGGCCGAATAGGAACAGCTCCGGTCTACAGCTCCCAGCGTGAGCGACGCAGAAGACGGTGATTTCTGCATTTCCATCTGAGGTACCGGGTTCATCTCACTAGGGAGTGCCAGACAGTGGGCGCAGGCCA&hg=38&distance=10000&mask=0)).
In our case, the intronic insertion leads to the integration of a pseudo exon between two native exons, because a new acceptor and a new donor splice site are created within this inserted sequence. We validated our results via PCR and Sanger sequencing, so we are sure that this really is the case.
A manuscript to publish the case study is still in preparation. We wanted to check afterwards, whether SpliceAI would be able to predict that and somehow it did – in the SpliceAI lookup you can clearly see the Acceptor Gain with 1.00 and the Donor Gain with 0.99. However, the pre-mRNA position is for both “0 bp”.

![spliceai_long_insertion](https://github.com/broadinstitute/SpliceAI-lookup/assets/83640817/fa4fe545-9d27-4338-9693-6e80dcd4caa3)

The pre-mRNA position is dependent on the (genomic) reference sequence and as the insertion does not occur in the reference sequence, a splice site gain within the insertion is not possible to display with a pre-mRNA position value.
And that is also the reason for @NM-G08 's “deviating” base positions based on the pre-mRNA position, because it is very likely that the new acceptor arises within the insertion, which can only be described as “pre-mRNA position 0” from SpliceAI.
For deletions, the prediction doesn’t have any problems with the position, because in the reference sequence, the affected deleted positions are still all there. So only for insertions(/duplications), that problem occurs.

Therefore, we have a follow-up question for @bw2 or @kdahlo : Would it somehow be possible to deal with those cases in a way that we could get a delta position leading to a position within the inserted/alternative sequence?
However, the pre-mRNA position based on the alternative sequence can only be done for insertions. The reference sequence has to be used for every other variant type (or at least all deletions).

Thank you for maintaining SpliceAI and the SpliceAI Lookup Tool!

Best,
Alex

**Comment by bw2** [comment]
I'm not sure I understand the issue. Please reopen if the issue still exists after recent updates.
