### ISSUE TITLE
Pangolin ERROR: Pangolin was unable to compute scores for this variant

### ISSUE THREAD

**Issue by Azjer2014** [broadinstitute/SpliceAI-lookup#34]
I've been encountering an error while using SpliceAI-lookup, which states: '**Pangolin ERROR: Pangolin was unable to compute scores for this variant.**' Despite this error, the program is still able to produce results; however, the results obtained from precomputed scores are very different from those generated by running SpliceAI-lookup. This might actually be an issue with the site/tool so you might want to take a look. This problem has been occurring since last week. 

[](url)
Screenshot:
<img width="1147" alt="SpliceAI" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/109017995/c18ba849-b132-4f4f-ab93-7a78b68cc25c">

**Comment by bw2** [comment]
Thanks, yes - Pangolin scores were broken on hg19. This is now fixed.

The difference between Illumina precomputed scores vs. the latest computed scores was sometimes due to the precomputed scores having been created using Gencode v24, while the latest scores are computed based on transcript sequences from Gencode v43. 
The use of precomputed scores were intended to speed up lookups but features added to the site since then have made them more of a liability and a source of confusion. Precomputed scores don't provide the raw score columns, non-coding transcripts, and other features, so I've now removed them from the site.

**Comment by Azjer2014** [comment]
Thanks for resolving the issue. It was great to have the choice of using precomputed scores. Yeah, the new features might cause some confusion at first, but people will get the hang of it in no time.

**Comment by bw2** [comment]
When/why would you want to use the precomputed scores?

**Comment by Azjer2014** [comment]
We use a file with precomputed scores for annotating VCF files in our pipeline, but when I use the website I almost always run the SpliceAI-lookup. I lookup precomputed scores on the website only when SpliceAI-lookup doesn't work or when there is a difference between the generated scores and my annotations.

**Comment by bw2** [comment]
ok, that makes sense.
re: "I lookup precomputed scores on the website only when SpliceAI-lookup doesn't work"
SpliceAI-lookup should work for all variants that have precomputed scores. If you have any examples of variants where this is not the case please create another bug report.
