### ISSUE TITLE
Results interpretation

### ISSUE THREAD

**Issue by emunte** [broadinstitute/SpliceAI-lookup#4]
Hi community,

I want to use SpliceAI to help me interpret variants detected routine diagnostics so I tested a variant where functional RNA studies indicate that it activates a cryptic splicing donor site: NM_007294.3: c.791_794del (BRCA1, minus strand)this variant enhances the alternative transcript

![image](https://user-images.githubusercontent.com/49304354/107051132-5e6b1f00-67cc-11eb-8168-f3b6d9104005.png)

To my surprise, 3 results are genereted -as can be seen in the picture. At first I thought they correspond to different transcripts, but the columns “variant” and “gene” give exactly the same information for the three outputs. I would need to know the difference between them in order to choose the more convenient for my aplication. Moreover, I would appreciate if you could help me to interpret the results. For instance, in the same example as before, SpliceAI says that the probability that an annotated position 8bp downstram my variant is used as a splice donor increases by 0.66. Then I’d suppose that the probability of using other donor site(s) in the surrounding 10,000 bp would decrease. However, the delta score of the donor loss is 0.00 for the masked option and 0.02 for the raw option, which to my knowledge means that the position whose probability of being used as donor has decreased most, has only decreased 0.02. So two questions come to my mind:
1) How can I interpret these results? Even if various positions decreased their scores, it seems unprobalbe that the most decreased one has decreased that little. It is true that the annotated donor for that exon in the main BRCA1 transcript has a low score according to most prediction algorithms, but still a higher decrease could be expected.
2) How can I know if the score of a new non-annotated donor in the variant sequence (not the delta score) will be higher or lower than the annotated one? Even when I see a donor gain and a donor loss, both significant, if I do not know the reference scores, I cannot know the alternative scores and compare them.

Thank you very much in advance,

Eli

**Comment by bw2** [comment]
Thank you for pointing out this issue. I just updated the site so that, when it generates scores by running the SpliceAI model, it processes each transcript separately and also displays ENST transcript ids in the results. Let me know if these updates help or hurt your ability to interpret the output.
Regarding your other comments, my understanding is that delta scores at different positions are independent of each other, and you can't infer that "..splice donor increases by 0.66. Then I’d suppose that the probability of using other donor site(s) in the surrounding 10,000 bp would decrease...".  The delta score at each position is only considering the score after introducing the variant vs. the score before introducing the variant, so each position's delta score may be affected in unintuitive ways.
 Also, I'm slowly working on a way to make the absolute (and not just the delta scores) more visible.
