### ISSUE TITLE
Different results for RAD51D depending on whether we select hg19 or hg38, even though there are no differences in the numbering

### ISSUE THREAD

**Issue by AndreaHAPS** [broadinstitute/SpliceAI-lookup#41]
Please paste the url of the results page and the variant search string as text here (unless this isn't about a specific variant).

Hi there,

We're looking at RAD51D:c.715C>G (NM_002878.4). When we put "RAD51D:c.715C>G" in the search bar and select hg 19 we get a donor gain of 0.87 at 3bp; when we then keep the same in the search bar but change to hg38 we loose that donor gain even though there is no difference in RAD51D between hg 19 and hg 38. Can you explain the difference? Which one is correct?

link to my search in hg 19:
https://spliceailookup.broadinstitute.org/#variant=RAD51D%3Ac.715C%3EG&hg=37&distance=500&mask=1

![hg19](https://github.com/broadinstitute/SpliceAI-lookup/assets/135933230/fac77535-1180-426e-a8cb-0fa8b245f07f)

link to my search in hg 38:
https://spliceailookup.broadinstitute.org/#variant=RAD51D%3Ac.715C%3EG&hg=38&distance=500&mask=1 
![hg38](https://github.com/broadinstitute/SpliceAI-lookup/assets/135933230/7e6f7a28-7645-4e14-80f0-c22a47f14329)

Thanks,
Andrea
---
If you'd like to also share a screenshot:
MacOS:   Press Command+Shift+4, select a region of the page, then paste the image here.
Windows:  Press Windows Logo Key + PrtScn   or   Fn + Windows logo key + Space Bar. Then, in File Explorer, open the Pictures > Screenshots folder and drag the image here.

**Comment by bw2** [comment]
Hi Andrea, 

SpliceAI-lookup use an Ensembl API to convert HGVS strings like "RAD51D:c.715C>G" into genomic coordinates before running SpliceAI on them. 
In your example, the API urls are

https://grch37.rest.ensembl.org/vep/human/hgvs/RAD51D:c.715C%3EG?content-type=application/json&vcf_string=1
which returns a "vcf_string" of `17-33430485-G-C`
and 

https://rest.ensembl.org/vep/human/hgvs/RAD51D:c.715C%3EG?content-type=application/json&vcf_string=1
which returns a "vcf_string" of `17-35103277-G-C`

However, these 2 positions aren't the same.

If I instead run hg19=>hg38 liftover on 17-33430485-G-C, I get [chr17-35103466-G-C](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr17:35103464-35103469) (rather than 17-35103277-G-C). Putting the lifted-over variant into SpliceAI-lookup for hg38 produces the [same scores as the hg19 variant](https://spliceailookup.broadinstitute.org/#variant=chr17-35103466-G-C&hg=38&distance=500&mask=1). 

Since the RAD51D gene definitions are the same for GRCh37 and GRCh38, my only guess is that the Ensembl API isn't using the same isoform when doing the conversion.  

Either way, this tells me that HGVS notation isn't as reliable/predictable as just specifying the genomic coordinates.
