### ISSUE TITLE
Clarification About SpliceAI Web Tool Version Updates

### ISSUE THREAD

**Issue by JAZ20030707** [broadinstitute/SpliceAI-lookup#52]
To whom it may concern,

Correct me if I am wrong, but SpliceAI web tool is constantly being updated. Does the methodology of the neural network change at all (i.e, the same variant can give a different output on different days) during these updates? If so, are such changes documented?

**Comment by bw2** [comment]
All updates are documented in the right sidebar. Most updates have been only superficial changes to the interface, or updates of the gencode gene model version (which can have an effect on scores for transcripts where the definition changed between gencode versions). The one recent non-superficial update was 
<img width="447" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/d1010e7d-84fc-4c74-9c06-43c2d2d133a9">
Otherwise, the reported scores should always be the same.
