### ISSUE TITLE
SpliceAI score issue

### ISSUE THREAD

**Issue by NYGHGenetics** [broadinstitute/SpliceAI-lookup#72]
Hi, 
Recently we have started to get an error message saying unable to reach the server. Any recommendations or explanations regarding the problem? 
Thanks!

![Screenshot 2024-03-14 142951](https://github.com/broadinstitute/SpliceAI-lookup/assets/163455140/609773b9-0043-45ae-b3a5-992397219620)

MacOS:   Press Command+Shift+4, select a region of the page, then paste the image here.
Windows:  Press Windows Logo Key + PrtScn   or   Fn + Windows logo key + Space Bar. Then, in File Explorer, open the Pictures > Screenshots folder and drag the image here.

**Comment by bw2** [comment]
Hi, I'm not seeing this error - for example, this variant returns scores as expected:

https://spliceailookup.broadinstitute.org/#variant=NM_001089.3(ABCA3)%3Ac.875A%3ET%20(p.Glu292Val)&hg=37&distance=500&mask=0&ra=1

Please share the url(s) or variants where you see this error.

**Comment by NYGHGenetics** [comment]
Hi,

Even for this variant I only see Pangolin scores and when you scroll down you can see Splice AI service error. Please see the secreenshot.

***@***.***

**Comment by NYGHGenetics** [comment]
Hi, 
This is another example. It only gives Pangolin scores but not SpliceAI. It gives Unable to reach server error message
https://spliceailookup.broadinstitute.org/#variant=Chr17%2066518889%20T%20G&hg=37&distance=500&mask=0&ra=0

**Comment by bw2** [comment]
SpliceAI scores often take longer to compute than Pangolin. Is it possible the request is just timing out?
Also, I just fixed caching on the server, so variants for which SpliceAI or Pangolin scores were previously requested by you or anyone else will now be returned immediately from memory instead of rerunning the models. 
Can you try accessing your link(s) again and see if the error still appears?

**Comment by NYGHGenetics** [comment]
I tried the links and the ones we had the scores before as well. It keeps giving same service error. We are using this website:
https://spliceailookup.broadinstitute.org/

thanks!

**Comment by bw2** [comment]
What browser are you using?
If you're using chrome, can you open https://spliceailookup.broadinstitute.org/
then click on Developer Tools in this menu:
<img width="613" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/8ed5ef06-837c-4659-bb5f-d0e9e7b2a5a4">
Then, click on the "Console" tab, and click the <img width="31" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/d7ea63ef-02d9-4314-a07e-f44ea3363d32">
  icon in the top left to clear previous messages:
<img width="238" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/bfdd736a-6287-4c98-9566-420ccb69396d">
Finally, enter your variant and click the Submit button on SpliceAI-lookup, and then share any errors that appear in this Developer Console. 
Your previous screenshot didn't show up on github, so you may need to upload it to github directly instead of putting it in an email response in order for me to see it.

Also, can you please try accessing the site from 1) a different browser and 2) a different network?  One way to do this is to access the website on your phone (as long as the phone is not connected to the same wifi as your computer).

**Comment by NYGHGenetics** [comment]
Hi, 
Please see the screenshot of error in developer tool.
![Screenshot 2024-03-15 151509](https://github.com/broadinstitute/SpliceAI-lookup/assets/163455140/287be1dd-1304-4559-9abb-ec6e77a197c9)

**Comment by bw2** [comment]
That's helpful. For some reason, the SpliceAI requests have started triggering cross-origin request security errors for what I'm assuming is a small number of users. I just updated the website to change some details of how these requests are made. Can you check to see if that resolved the issue?
