### ISSUE TITLE
follow up of issue #67, #69

### ISSUE THREAD

**Issue by HJin2024** [broadinstitute/SpliceAI-lookup#84]
I have a similar situation reported in the issue #67 & #69. I would like to find out how I can check if the SpliceAI scores are real or due to the technical artefact? Is there a way to check this on SpliceAI webpage? 
Thanks a lot

**Comment by bw2** [comment]
When you enter your variant, do you see the warning described in 
https://github.com/broadinstitute/SpliceAI-lookup/issues/69 ?
![image](https://github.com/user-attachments/assets/d01e4ef8-dd0d-4ad0-9d3f-cf0e62997ecb)

**Comment by bw2** [comment]
I was thinking of adding a table like the example in 
https://github.com/broadinstitute/SpliceAI-lookup/issues/69#issue-2172730864

<img width="642" alt="image" src="https://github.com/user-attachments/assets/27d23f08-5f6a-4394-8660-7daaa506e5af">

Do you agree a table like this would address your question?

**Comment by HJin2024** [comment]
Yes definitely. The reason I raised this issue here is to get a table like that. Is it possible for SpliceAi provide the table automatically with a link in the cases like this?

Thanks a lot
Huilin

**Comment by bw2** [comment]
I've now added this table to a popup for variants where the warning appears:

<img width="1262" alt="image" src="https://github.com/user-attachments/assets/aca6ebb3-7afd-474c-812e-d7b2b9b675b9">

**Comment by bw2** [comment]
For example:
https://spliceailookup.broadinstitute.org/#variant=13-21155151-C-CAGTTTTCTTTGTTGCTGACATCTCGGATGTTCTGTCCATGTTTAAGGAACCTTTTACTGGGTA&hg=38&bc=basic&distance=500&mask=0&ra=0

**Comment by HJin2024** [comment]
Hi Ben

Many thanks for your time. I like the table and it’s very helpful. But my question is actually how to generate this table for my own variant (chr6-56617985-C-CCT, hg38).
I was hoping this table would appear in SpliceAI along with the warning message, just like you did in the example.

KR
Huilin

**Comment by bw2** [comment]
It was showing cached results from before the feature was added. If you reload the page, you should see the new tables.

**Comment by HJin2024** [comment]
Yes! That’s fabulous! Thanks a million. Will this table be added along with the warning message for other similar variants as well? I just don’t want to trouble you or other SpliceAI colleagues each time for the same query.

KR
Huilin

**Comment by bw2** [comment]
Hi Huilin, yes, the table appears for any variant that has that warning.

**Comment by bw2** [comment]
Also, based on additional feedback, instead of the warning icon, we now just show the exact position in the main table, along with the icon that brings up the detailed table. [[example](https://spliceailookup.broadinstitute.org/#variant=13-21155151-C-CAGTTTTCTTTGTTGCTGACATCTCGGATGTTCTGTCCATGTTTAAGGAACCTTTTACTGGGTA&hg=38&bc=basic&distance=500&mask=0&ra=0)]

<img width="445" alt="image" src="https://github.com/user-attachments/assets/736c8e44-0343-4848-8060-ade9da9a5b7d">

**Comment by amartins1** [comment]
Hi,
When I tried to visualize the example indicated in your message below and clicked on the icon, I did see a table popping up on the bottom left but only partially. It seems that it does not properly fit on the screen of my laptop computer. Impossible to scroll further to the right.Difficult to inspect the full table even when I resize the screen
All best;
Alexandra

Le Mercredi, Novembre 13, 2024 22:30 CET, Ben Weisburd ***@***.***> a écrit:
 
 
Also, based on additional feedback, instead of the warning icon, we now just show the exact position in the main table, along with the icon that brings up the detailed table. [example]image.png (view on web)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/broadinstitute/SpliceAI-lookup/issues/84#issuecomment-2474826939", "url": "https://github.com/broadinstitute/SpliceAI-lookup/issues/84#issuecomment-2474826939", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
-- 
Alexandra Martins, PhD, HDR
Inserm Researcher (CRHC)
Group Leader
Inserm UMR 1245 - Cancer and Brain Genomics
UFR Santé
22 Bvd Gambetta
CS 76183
76183 Rouen Cedex 1
France
phone#: + 33 (0)2 35 14 83 14
email: ***@***.***
https://www.researchgate.net/profile/Alexandra_Martins5
ORCID ID: 0000-0003-4322-8497

**Comment by bw2** [comment]
Hi Alexandra, what browser and operating system are you using?

**Comment by HJin2024** [comment]
Hi Ben

The table is showing correctly on my laptop for my variant. I use google chrome. And I like the updated version “instead of the warning icon, we now just show the exact position in the main table, along with the icon that brings up the detailed table”!

Thanks a lot
Huilin

**Comment by bw2** [comment]
Thanks Huilin

**Comment by amartins1** [comment]
Dear Ben,
Thanks for your prompt reply
In my laptop I use
- mozilla firefox (browser)
- microsoft windows 11 family (operating system)
All best,
Alexandra

Le Jeudi, Novembre 14, 2024 01:11 CET, Ben Weisburd ***@***.***> a écrit:
 
 
Hi Alexandra, what browser and operating system are you using?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/broadinstitute/SpliceAI-lookup/issues/84#issuecomment-2475079172", "url": "https://github.com/broadinstitute/SpliceAI-lookup/issues/84#issuecomment-2475079172", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
-- 
Alexandra Martins, PhD, HDR
Inserm Researcher (CRHC)
Group Leader
Inserm UMR 1245 - Cancer and Brain Genomics
UFR Santé
22 Bvd Gambetta
CS 76183
76183 Rouen Cedex 1
France
phone#: + 33 (0)2 35 14 83 14
email: ***@***.***
https://www.researchgate.net/profile/Alexandra_Martins5
ORCID ID: 0000-0003-4322-8497

**Comment by bw2** [comment]
@amartins1  I have not been able to reproduce the issue in Firefox. 
Let me know if it's still a problem.

**Comment by bw2** [comment]
Just in case it's still an issue on some browsers, I've added an option to display the table in a separate popup dialog:

<img width="546" alt="image" src="https://github.com/user-attachments/assets/0618eeaa-e1bd-42a8-bb29-fa5849dcf6e0">

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/b1d3413f-9a23-4c67-9d16-1636e77b6934">

**Comment by amartins1** [comment]
Great. Thanks!

Le Mercredi, Décembre 04, 2024 15:46 CET, Ben Weisburd ***@***.***> a écrit:
 
 
Just in case it's still an issue on some browsers, I've added an option to display the table in a separate popup dialog:image.png (view on web) image.png (view on web)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***> 
--
Alexandra Martins, PhD, HDR
Inserm researcher (CRHC)
Group Leader
INSERM U1245, Cancer and Brain Genomics (CBG)
UFR Santé, Univ Rouen Normandie
22 Boulevard Gambetta
76183 Rouen
France
phone# (office): + 33 0(2) 35 14 83 14
email: ***@***.***
ORCID: 0000-0003-4322-8497
